### ISSUE TITLE
Retorno do Problema dos Capítulos e Seções

### ISSUE THREAD

**Issue by GabrielAment** [ajholanda/modelos-ppgca#1]
Boa tarde Adriano,
Conforme estávamos conversando via e-mail, baixei o novo template aqui no github e coloquei no meu Overleaf. Realmente, o problema do cabeçalho foi resolvido, muito obrigado! Porém, com a resolução desse último problema, o problema anterior, dos capítulos e seções repetindo o titulo logo em seguida retornou (que foram resolvidos com a adição de "\renewcommand{\chaptermark}[1]{}" e "\renewcommand{\sectionmark}[1]{}").
Quando comento a parte do "\pagestyle{fancy}" e "\fancyhf{}", o problema que comentei some (não mostra mais em duplicidade os títulos dos capítulos e seções), mas ai o problema com o cabeçalho retorna.
Poderia me ajudar, por favor, com esse caso?
Obrigado!

**Comment by ajholanda** [comment]
O problema era gerado por uma variável chamada `\mark` definida no arquivo principal LaTeX `main.tex`. Após mudança de nome da variável para `\mymark` usando `\newcommand{\mark}{$\star$}`, os erros de início de capítulo/seção e cabeçalho foram corrigidos. O pacote `\fancyhdr` foi desabilitado (comentado), mas ele pode ser utilizado no arquivo principal seguindo a documentação do pacote e tomando cuidado com conflitos com estilos já definidos em `ppgca.cls`.
